import { Product } from 'src/types/product'

export const MOCK_PRODUCTS: Product[] = [
  {
    productId: 'prod2',
    name: 'Running Shoes',
    price: 89.99,
    category: 'Footwear',
    rating: 4.8,
    imageUrl: 'https://media.gettyimages.com/id/185246744/photo/sports-shoe.jpg?s=612x612&w=0&k=20&c=d3KKioU6TLO_iyUdA0f-1BxKxBByR_8tU0I6FpMZzX8=',
    colors: ['Black', 'White', 'Blue'],
    description: 'Lightweight running shoes with excellent grip',
  },
  {
    productId: 'prod3',
    name: 'Yoga Mat',
    price: 29.99,
    category: 'Equipment',
    rating: 4.5,
    imageUrl: 'https://media.gettyimages.com/id/184883473/photo/exercise-mat.jpg?s=612x612&w=0&k=20&c=uXUfuhuTQw3Nm1l2gzucncGDA72JZVkQ8fB3bhLe5Sw=',
    colors: ['Purple', 'Green', 'Peach'],
    description: 'Non-slip yoga mat for home practice',
  },
  {
    productId: 'prod4',
    name: 'Dumbbell Set',
    price: 59.99,
    category: 'Equipment',
    rating: 4.6,
    imageUrl: 'https://media.gettyimages.com/id/185285227/photo/dumbbell.jpg?s=612x612&w=0&k=20&c=6rCmJPBJ-smvGJvjrSUHdhbt1oPbuUzokThBI_mY5NY=',
    colors: ['Black', 'Silver'],
    description: 'Adjustable dumbbell set for strength training',
  },
  {
    productId: 'prod5',
    name: 'Gym Bag',
    price: 39.99,
    category: 'Accessories',
    rating: 4.4,
    imageUrl: 'https://media.gettyimages.com/id/184094505/photo/black-blue-duffel-bag.jpg?s=612x612&w=0&k=20&c=bgWmM2SlfYR6X4BrSUwD1Cz49qQpIvjSSpMz9aB82gk=',
    colors: ['Gray', 'Black', 'Navy'],
    description: 'Spacious gym bag with waterproof compartments',
  },
  {
    productId: 'prod6',
    name: 'Fitness Tracker',
    price: 79.99,
    category: 'Accessories',
    rating: 4.3,
    imageUrl: 'https://media.gettyimages.com/id/1454820603/photo/overhead-of-young-woman-using-fitness-app-on-smartphone-and-smartwatch-to-monitor-training.jpg?s=612x612&w=0&k=20&c=EsIJ69wOyn1YX_2lRUcsT6zqS6t4uPHqPOIr7ZDWyew=',
    colors: ['Black', 'Pink', 'Blue'],
    description: 'Smart fitness tracker with heart rate monitor',
  },
  {
    productId: 'prod7',
    name: 'Training Shorts',
    price: 24.99,
    category: 'Activewear',
    rating: 4.2,
    imageUrl: 'https://media.gettyimages.com/id/500284669/photo/portrait-of-gymer-smiling-at-camera.jpg?s=612x612&w=0&k=20&c=RR04loMkKn8-Hv-P4rJh-l3n6-42ubfYRj6IwL0uMXw=',
    colors: ['Red', 'Black'],
    description: 'Breathable shorts for intense workouts',
  },
  {
    productId: 'prod8',
    name: 'Foam Roller',
    price: 19.99,
    category: 'Equipment',
    rating: 4.5,
    imageUrl: 'https://media.gettyimages.com/id/1187356524/photo/stretching-her-upper-back.jpg?s=612x612&w=0&k=20&c=IN44PIbOSrLZC5iQc7bSzijDc0G78OK1AgwVpsti3no=',
    colors: ['Blue', 'Gray'],
    description: 'High-density foam roller for muscle recovery',
  },
  {
    productId: 'prod9',
    name: 'Water Bottle',
    price: 14.99,
    category: 'Accessories',
    rating: 4.6,
    imageUrl: 'https://media.gettyimages.com/id/1437580240/photo/close-up-of-a-reusable-water-bottle-in-a-human-hand-concept-of-thirst-rehydration-and.jpg?s=612x612&w=0&k=20&c=bzAvpGdeXn--IyK2k8R-Gn7WkSahZFd94h-DahcDe2w=',
    colors: ['Green', 'Black', 'Blue'],
    description: 'Insulated stainless steel water bottle',
  },
  {
    productId: 'prod10',
    name: 'Compression Socks',
    price: 18.99,
    category: 'Accessories',
    rating: 4.1,
    imageUrl: 'https://media.gettyimages.com/id/1141855272/photo/cross-country-running-detail-femal-legas-with-compression-socks-and-sport-shoes.jpg?s=612x612&w=0&k=20&c=ViLS-BbEZkuEsAMJSjT-7_NG3TPKYZErNDSX6c2yf6g=',
    colors: ['White', 'Black'],
    description: 'Supportive socks to improve blood circulation',
  },
]

export const MOCK_CUSTOMER_DATA = {
  customerName: 'Le Tien Dat',
  paymentDetails: {
    cvv: '123',
    cardNumber: '1234-5678-9012-3456',
    expirationDate: '12/25',
  },
}
